### ISSUE TITLE
AssertionError: The MinkowskiEngine was compiled with CPU_ONLY flag

### ISSUE THREAD

**Issue by samanemami** [lyp22/ResSCNN#5]
When I am compiling the `train.py`, it returns the following error.
When I was installing `MinkowskiEngine` I used the pip that in the `setup.py` there is `torch.cuda.is_available()` by default!
I tried to move the method to `cuda` but did not work

```log

/home/saman/anaconda3/envs/py37/lib/python3.7/site-packages/MinkowskiEngine/__init__.py:225: UserWarning: The MinkowskiEngine was compiled with CPU_ONLY flag. If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.
  "If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.",
2022-11-22 11:03:47,975 - /home/saman/ResSCNN/lib/Logging.py[line:25] - INFO: ResSCNN(
  (conv1): MinkowskiConvolution(in=3, out=64, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
  (norm1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block1): BasicBlock(
    (conv1): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (conv2): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
  (norm2): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block2): BasicBlock(
    (conv1): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (conv3): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
  (norm3): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block3): BasicBlock(
    (conv1): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (conv4): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
  (norm4): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  (block4): BasicBlock(
    (conv1): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
    (conv2): MinkowskiConvolution(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
    (norm2): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.05, affine=True, track_running_stats=True)
  )
  (glob_avg): AdaptiveMaxPool2d(output_size=(1, None))
  (fc1): Linear(in_features=256, out_features=32, bias=True)
  (fc2): Linear(in_features=32, out_features=1, bias=True)
)
  0%|                                                       | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/saman/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/saman/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/saman/ResSCNN/train.py", line 55, in <module>
    main(config)
  File "/home/saman/ResSCNN/train.py", line 47, in main
    trainer.train()
  File "/home/saman/ResSCNN/lib/trainer.py", line 111, in train
    val_dict,plcc,srocc = self._test_epoch(0)
  File "/home/saman/ResSCNN/lib/trainer.py", line 247, in _test_epoch
    stensor = ME.SparseTensor(feats[0].to(self.device), coordinates=coords[0].to(self.device))
  File "/home/saman/anaconda3/envs/py37/lib/python3.7/site-packages/MinkowskiEngine/MinkowskiSparseTensor.py", line 252, in __init__
    minkowski_algorithm=minkowski_algorithm,
  File "/home/saman/anaconda3/envs/py37/lib/python3.7/site-packages/MinkowskiEngine/MinkowskiCoordinateManager.py", line 138, in __init__
    ), "The MinkowskiEngine was compiled with CPU_ONLY flag. If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine."
AssertionError: The MinkowskiEngine was compiled with CPU_ONLY flag. If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.
```

**Comment by lyp22** [comment]
You can try `torch.cuda.is_available()`. If it returns `False`, the question is in Pytorch and Pytorch may be installed for CPU only.

**Comment by lyp22** [comment]
When installing Pytorch, `conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch` is for GPU. And the command `conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cpuonly -c pytorch` is for CPU.

**Comment by samanemami** [comment]
Thanks,
But could we continue working with the CPU?

Is it possible?

**Comment by samanemami** [comment]
> You can try `torch.cuda.is_available()`. If it returns `False`, the question is in Pytorch and Pytorch may be installed for CPU only.

I installed the `PyTorch` for `GPU`, but yes, it returned `False`.
I did some research and I found that apparently, my machine (`chrome://gpu`) does not support `Cuda` .

I was wondering, may we use CPU with your library?

**Comment by lyp22** [comment]
> Thanks, But could we continue working with the CPU?
> 
> Is it possible?

Yes, you can delete all `.cuda()` and `.to(device)` in the code, but it will be very very slow.

**Comment by samanemami** [comment]
Thank you
